In [3]:
!pip install pandas nltk
import pandas as pd
import nltk
nltk.download('punkt')
nltk.download('stopwords')

Requirement already satisfied: pandas in d:\vs code\infosys\infosys-langgraph-email-assistant-group2\venv\lib\site-packages (2.3.3)
Requirement already satisfied: nltk in d:\vs code\infosys\infosys-langgraph-email-assistant-group2\venv\lib\site-packages (3.9.2)
Requirement already satisfied: numpy>=1.26.0 in d:\vs code\infosys\infosys-langgraph-email-assistant-group2\venv\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\vs code\infosys\infosys-langgraph-email-assistant-group2\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\vs code\infosys\infosys-langgraph-email-assistant-group2\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\vs code\infosys\infosys-langgraph-email-assistant-group2\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: click in d:\vs code\infosys\infosys-langgraph-email-assistant-group2\venv\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in d:\vs code\infosys\infosys-langgraph-email-assistant-group2\venv\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in d:\vs code\infosys\infosys-langgraph-email-assistant-group2\venv\lib\site-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in d:\vs code\infosys\infosys-langgraph-email-assistant-group2\venv\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: six>=1.5 in d:\vs code\infosys\infosys-langgraph-email-assistant-group2\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in d:\vs code\infosys\infosys-langgraph-email-assistant-group2\venv\lib\site-packages (from click->nltk) (0.4.6)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\shahi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shahi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [6]:
df = pd.read_csv("../data/email_evaluation_dataset_mohammadshahidulla.csv")
df.head()

,id,email_text,expected_action,expected_tone
0,1,This is a weekly newsletter with general updat...,notify,neutral
1,2,"Congratulations, you have been selected for th...",notify,urgent
2,3,Your order has been shipped and will be delive...,notify,polite
3,4,Reminder: The project review meeting is schedu...,notify,urgent
4,5,Your order has been shipped and will be delive...,ignore,urgent

In [7]:
import pandas as pd
import numpy as np
import re

In [9]:
df['clean_text'] = (
    df['email_text']
    .str.lower()
    .str.replace('[^a-zA-Z ]', '', regex=True)
)

df[['email_text', 'clean_text']].head()

,email_text,clean_text
0,This is a weekly newsletter with general updat...,this is a weekly newsletter with general updat...
1,"Congratulations, you have been selected for th...",congratulations you have been selected for the...
2,Your order has been shipped and will be delive...,your order has been shipped and will be delive...
3,Reminder: The project review meeting is schedu...,reminder the project review meeting is schedul...
4,Your order has been shipped and will be delive...,your order has been shipped and will be delive...

In [11]:
def email_assistant(clean_text):
    text = clean_text.lower()
    if "urgent" in text or "submit" in text or "deadline" in text:
        return "notify","urgent"
    elif "thank you" in text:
        return "respond","polite"
    else:
        return "respond","neutral"